Use @override_settings(DEBUG=...) in tests and fix breaking tests
When running whole test suite after adding 2 tests with @override_settings(DEBUG=...), ~100 random tests started breaking. Error:
FAILED tests/structure/test_views.py::test_property_enum_item_update - Failed: Undefined template variable 'logged_in_user' in '/home/runner/work/katalogas/katalogas/vitrina/templates/component/navbar.html'

Turns out, these tests break if running with DEBUG=True, because logged_in_user variable is used in navbar.html which is one of base HTMLs, but it is set in only one view. Turns out it's not neede at all.